name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests
        uses: ./gradlew clean test
#
#            - name:Run tests
#            - run: ./gradlew clean test
#
#            - name:Build artifact
#            - run:./gradlew build
#
#            - name: Publish artifact
#            - uses: actions/upload-artifact@v3
#            - with:
#                path: build/libs
